### ISSUE TITLE
Improved support for MuseScore 3 needed (and provided)

### ISSUE THREAD

**Issue by DLLarson** [jgadsden/tin-whistle-tablature#12]
Hi,

The current (circa June 2019) MuseScore version 3 of the tin-whistle-tablature plug-in is missing many great features compared to the MS v2 version.

I've taken this working on and fixed the MuseScore 3.x QML missing scripting feature required to properly select whistle keys and scales (i.e., property 'instrumentId').

In addition, I've modified the plug-in to place the tab images under the staff just like the 2.0 version provided.

Finally, I updated the example scores files and README.md images to reflect these improvements.

This all available in the following pull request:

https://github.com/jgadsden/tin-whistle-tablature/pull/11

Thanks for considering these changes!

Dale

**Comment by DLLarson** [comment]
The MuseScore 3 project has now merged the instrumentId fix for the 3.2 release.

-Dale

**Comment by jgadsden** [comment]
Hello Dale - excellent changes, good to see the plugin making much more sense.  Sorry for the delay in approving the commit, it was a hectic weekend / Monday for me ... too much rail travel (I do not do air travel).

**Comment by DLLarson** [comment]
Sweet! 

>(I do not do air travel).

You computer security guys don't want the airplane to be hacked in the air? ;)
A prudent choice. When I saw the OP-TEE reference I knew you are hard core.

Thanks!
Dale

**Comment by jgadsden** [comment]
Most excellent work @DLLarson, thanks again for pull request #11 and closing this issue.

**Comment by DLLarson** [comment]
Thanks!

Dale
