### ISSUE TITLE
Added improved grace note support.

### ISSUE THREAD

**Issue by DLLarson** [jgadsden/tin-whistle-tablature#14]
See PR  https://github.com/jgadsden/tin-whistle-tablature/pull/13

Thanks!

-Dale

**Comment by DLLarson** [comment]
I'm in the hunt for fixing the trailing grace note issue. It's kinda weird in its implement.

**Comment by DLLarson** [comment]
I also completed work on enabling leading and trailing grace notes with the plug in. To see the plugin look here:

https://github.com/DLLarson/tin-whistle-tablature/tree/lead-trail-grace-working

Obviously I won't be submitting that one until I'm sure MuseEdit will accept my patch for adding the Note.noteType propertly.

-Dale

**Comment by DLLarson** [comment]
Commits are reading to be deployed.

-Dale

**Comment by jgadsden** [comment]
Thanks again for coding on this project, very good to see these changes go in.
