### ISSUE TITLE
MuseScore 3 plugin no longer executes

### ISSUE THREAD

**Issue by jgadsden** [jgadsden/tin-whistle-tablature#16]
When invoking the plugin in the latest MuseScore 3 (version 3.2.3.22971) the plugin fails to run withconsole message:

Running…
Creating component failed
   line 63: Expected token `;'
   line 63: Expected token `;'

When the function dumpObjectEntries() is removed using the builtin 'Plugin Creator' tool the plugin works as expected.

**Comment by DLLarson** [comment]
The reason this breaks is that the Windows version of ECMAScript is newer than the version used on the Mac platform. It was discovered a while ago but the fix is still in my PR for the 3.3 release.

That broken diagnostic has been recoded to work in the older ECMAScript in commit.

-Dale
