### ISSUE TITLE
Plugin development joint effort

### ISSUE THREAD

**Issue by eduardomourar** [jgadsden/tin-whistle-tablature#28]
@jgadsden , How about we use the [this plugin](https://github.com/eduardomourar/fingering-diagram) to concentrate most fingering diagrams?

We can either create a new section in the Fiati music font or extend the recorder section.

If you are interested, you can just use [this spreadsheet](https://github.com/eduardomourar/fingering-diagram/blob/master/fingering.ods) to check the recorder fingering I placed already.

**Comment by jgadsden** [comment]
Hello @eduardomourar - yes, this looks a good idea. Do you want to create a new section? There are many tuning for Tin Whistles, and also Low Whistles, so this would be good for a new section

**Comment by eduardomourar** [comment]
@jgadsden , just like you have already mentioned, I was thinking in have a new section within fiati for `simple systems` that will have all the different options of whistles. I will probably need some help to convert the the base fingering into a spreadsheet format (like this [here](https://github.com/eduardomourar/fingering-diagram/blob/master/fingering.ods)), because then we can easily make the mapping from note to font characters later.

**Comment by jgadsden** [comment]
yes, happy to help. I am not sure that I understand the spreadsheet yet ... if you could create a branch with a modified spreadsheet? Then advise me on what info is required?

**Comment by eduardomourar** [comment]
Done. I have created a new tab called `Tin_Whistle` on this branch: https://github.com/eduardomourar/fingering-diagram/blob/feature/add-whistles/fingering.ods
You can just fill columns B through L with what is the fingering for each written note. Let's say that we use the convention `1` for fully covered hole, `2` half covered.

**Comment by jgadsden** [comment]
Hello @eduardomourar - thankyou, and I can see the new tab in the spreadsheet on the add-whistles branch. A couple of things that are tripping me up:

- All six holes closed will give a D4, as you show, but only for a D Low Whistle. All holes closed for a D Tin Whistle will produce a D5 - and I do not know how to show this in the spreadsheet. In effect they are different instruments?
- We can go up an octave on all the Whistles by altering the breath, and this is shown with a '+' above the fingering diagram. I could not see it on the SMuFL document, so is this possible? It is also possible to go up two octaves (I am no where near proficient enough to do this) and this is marked with '++'

Not sure what to do, if you could advise me?

**Comment by eduardomourar** [comment]
You can just worry about D Tin Whistle in the spreadsheet and don't worry about the written note (as you can see in column K the MIDI channel is one octave higher). I will take the fingering for D Tin Whistle and transpose it to the other instruments just like you did in your plugin code. If you feel that is a need for unique fingering in the other instruments, a new tab can be created for each.

Regarding the '+' symbol, you can see that we are not following the SMuFL standard in its full because it does not include fingering charts per se in the specification, so we only follow guidelines such as: zero width glyphs, use unicode proper range, etc. But we are going to incorporate the plus symbols, so you can use column `UpperOctave` for the first octave. If you think there is a need to have the second octave there already, you can just create a new column for that.

**Comment by jgadsden** [comment]
Spreadsheet updated in pull request https://github.com/eduardomourar/fingering-diagram/pull/13
