### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by jebbgrenham** [jgadsden/tin-whistle-tablature#34]
Download links in the musescore page and the github readme are all 404-ing.

**Comment by jgadsden** [comment]
Many thanks for letting me know @jebbgrenham , I did some branch renaming and totally forgot about the download links.
The links in MuseScore plugin page now work, and updated github readme links as well.
Thanks again for raising this issue

**Comment by jgadsden** [comment]
Closing this now because I think I have tracked down all the broken links.
