### ISSUE TITLE
Plugin no longer works with MuseScore 4.1.0

### ISSUE THREAD

**Issue by antman2** [jgadsden/tin-whistle-tablature#36]
Despite having only a single staff with a "D Tin Whistle" instrument, after upgrading from MuseScore 4.0.2.230651546 to 4.1.0.231921401 the "Tin Whistle Tablature" plugin stops working with the error message:

> No selected staff in the current score uses a tin whistle instrument.
>
> Use tab "Instruments -> Add" to select instruments.

Downgrading back to 4.0.2.230651546 restores functionality.

**Comment by jgadsden** [comment]
Thanks @antman2 for finding this, if you have a fix then that would be great - otherwise I will try and look at it when I can, hope within the next couple of weeks

**Comment by jgadsden** [comment]
Hello @antman2 , found the problem : the instrumentId changed for version 4.0.x and then changed back again for 4.1
working on a new release that will support both

**Comment by jgadsden** [comment]
@antman2 there is a new release at https://github.com/jgadsden/tin-whistle-tablature/releases/tag/v4.1
and also the project page is updated at : https://musescore.org/en/project/tin-whistle-tablature

Seems to work OK for me on version 4.1 (and earlier) - hope it works OK for you now

**Comment by antman2** [comment]
@jgadsden thank you, I can confirm that it's now working for me in both 4.0.2.230651546 as well as the current 4.1.0.231921401 (macOS).
