### ISSUE TITLE
Tabs appear over a second staff

### ISSUE THREAD

**Issue by dkovar** [jgadsden/tin-whistle-tablature#38]
If you are working with a score for two instruments such as Scarborough Fair (Arranged for recorder / tin whistle duet) from MuseScore.com the tabs appear over the second staff.

<img width="911" alt="Screen Shot 2024-02-17 at 12 36 40 PM" src="https://github.com/jgadsden/tin-whistle-tablature/assets/2086992/8f24cc33-c220-4eae-a379-e1fd29d833c1">

This is with MuseScore - OS: macOS 12.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

And the latest plugin version.

**Comment by jgadsden** [comment]
Hello @dkovar , this is a very good point
we could not see a way round it though, and the only suggestion I have is to only tab one whistle and make sure it is the lowest staff
Very open to any better suggestions than this, if you can find one?

**Comment by dkovar** [comment]
I suspect this is an edge case and not worth addressing.
