### ISSUE TITLE
Generated tabs are not corrected if you change a note and regenerate

### ISSUE THREAD

**Issue by uthidata** [jgadsden/tin-whistle-tablature#39]
For the tin whistle in D,
if I have an A note and generate tabs via the plugin, it works as expected:
![image](https://github.com/jgadsden/tin-whistle-tablature/assets/19877789/93e8ffbe-a6fe-4ca8-8480-8152ef827a45)

If I change said note to B and regenerate tabs, the new tab is overlaid on the old tab:
![image](https://github.com/jgadsden/tin-whistle-tablature/assets/19877789/ba26257d-8aa7-4d53-9259-81b2b6bde65e)

resulting in wrong-looking tabs.
In the image, the first note actually has 2 tabs, and the "newer" one has one hole covered, but because it is overlaid on the one with 2 holes covered, the second hole is still black.

Is it possible to delete previously generated tabs before creating new ones?

**Comment by jgadsden** [comment]
Not at the moment @uthidata , but if you want to take a look at this and see if it can be implemented? that would be great

**Comment by uthidata** [comment]
@jgadsden I created a PR for it.
