### ISSUE TITLE
Do not apply tabs to tied notes in MuseScore 3

### ISSUE THREAD

**Issue by jgadsden** [jgadsden/tin-whistle-tablature#5]
MuseScore version 2 plugin checks for tied notes and does not display the tab. Note that this is different from slurs.

Suggest a check in MuseScore 3 is made along the lines of:

```
                if (notes[i].tieBack != null) {
                    // No tab if the note is tied
                    // Pas de tablature si la note est une note liée
                    tab = ""
                } 
```

so that tied notes do not have tabs applied to them, as this gets too crowded and is not needed.

**Comment by jgadsden** [comment]
Also consider not showing the tab if it is the same note as the last one, as there is no need to repeat it.

**Comment by aayala4** [comment]
when I was exploring this with musescore 3, it didn't appear that the note object revealed the tieBack field yet in the most recent version. I guess [several fields are still missing](https://musescore.org/en/node/282107) for api development in v3

**Comment by jgadsden** [comment]
Yes, agreed, much of the Plugin API for MuseScore is yet to be implemented and the other issues are waiting on this as well.

Most users seem to be still on MuseScore 2 (version 3 was publicly announced last month), so I guess will not be too concerned for the moment.  We can keep an eye on the version 3 Plugin API, and then apply the fix to master when it becomes available.
